---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: charts
  namespace: chart-museum
secretDescriptor:
  backendType: secretsManager
  data:
    - key: chart-museum/username/dev
      name: username
    - key: chart-museum/password/dev
      name: password